baseURL = "https://mgurov.github.io/"
languageCode = "en-us"
title = "Mykola on Web"
theme = "mgurovblog"

[params]
    linkedin = "https://nl.linkedin.com/in/mgurov"
    mainSections = ["posts"]
    custom_css = ["css/custom.css"]
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    weight = 10
    details = "Learn more about me"

  [[menu.main]]
    name = "talks"
    url = "/talks/"
    weight = 20
    details = "The public speaking I do"

  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 30
    details = "random notes on random (tech) topics"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
