baseURL = "https://mgurov.github.io/blog/"
languageCode = "en-us"
title = "Mykola on blog"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-143346799-1"

[params]
    twitter = "ngurov"

[social]
    twitter = "https://www.twitter.com/ngurov"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    weight = 20

#  [[menu.main]]
#    name = "talks"
#    url = "/talks/"
#    weight = 30

  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 10