baseURL = "https://mgurov.github.io/blog/"
languageCode = "en-us"
title = "Mykola on blog"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-143346799-1"

[params]
    twitter = "ngurov"

[social]
    twitter = "https://www.twitter.com/ngurov"