baseURL = "https://github.com/mgurov/blog.git"
languageCode = "en-us"
title = "Mykola on blog"
theme = "hugo-cactus-theme"

[params]
    twitter = "ngurov"

[social]
    twitter = "https://www.twitter.com/ngurov"