baseURL = "https://mgurov.github.io/"
languageCode = "en-us"
title = "Mykola on blog"
theme = "gohugo-theme-ananke"
googleAnalytics = "UA-143346799-1"

[params]
    twitter = "https://www.twitter.com/ngurov"
    mainSections = ["posts"]
    custom_css = ["css/custom.css"]
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    weight = 20

  [[menu.main]]
    name = "talks"
    url = "/talks/"
    weight = 30

  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 10