name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: check where we are
      run: pwd
    - name: check where we are
      run: ls -lah
    - name: check whether we have our theme checked out
      run: ls -lah themes/gohugo-theme-ananke
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      #with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        #hugo-version: # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        #extended: # optional, default is false  
    - name: Build
      run: hugo --gc --minify --cleanDestinationDir    
