name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
            submodules: true
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.122.0 # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        #extended: # optional, default is false  
    - name: Build
      run: hugo --gc --minify --cleanDestinationDir
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public
        personal_token: ${{ secrets.ACTIONS_DEPLOY_PAGES }}
        external_repository: mgurov/mgurov.github.io
        publish_branch: master
